// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package media

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	InstallESD     *string `mapstructure:"installesd" cty:"installesd" hcl:"installesd"`
	User           *string `mapstructure:"user" cty:"user" hcl:"user"`
	AuthorizedKey  *string `mapstructure:"authorized_key" cty:"authorized_key" hcl:"authorized_key"`
	OpenSSH        *bool   `mapstructure:"openssh" cty:"openssh" hcl:"openssh"`
	Updates        *string `mapstructure:"updates" cty:"updates" hcl:"updates"`
	ExtraSpaceMiB  *int    `mapstructure:"extra_space_mib" cty:"extra_space_mib" hcl:"extra_space_mib"`
	PrivopsTimeout *string `mapstructure:"privops_timeout" cty:"privops_timeout" hcl:"privops_timeout"`
	CacheDir       *string `mapstructure:"cache_dir" cty:"cache_dir" hcl:"cache_dir"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"installesd":      &hcldec.AttrSpec{Name: "installesd", Type: cty.String, Required: false},
		"user":            &hcldec.AttrSpec{Name: "user", Type: cty.String, Required: false},
		"authorized_key":  &hcldec.AttrSpec{Name: "authorized_key", Type: cty.String, Required: false},
		"openssh":         &hcldec.AttrSpec{Name: "openssh", Type: cty.Bool, Required: false},
		"updates":         &hcldec.AttrSpec{Name: "updates", Type: cty.String, Required: false},
		"extra_space_mib": &hcldec.AttrSpec{Name: "extra_space_mib", Type: cty.Number, Required: false},
		"privops_timeout": &hcldec.AttrSpec{Name: "privops_timeout", Type: cty.String, Required: false},
		"cache_dir":       &hcldec.AttrSpec{Name: "cache_dir", Type: cty.String, Required: false},
	}
	return s
}

// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDatasourceOutput struct {
	Path              *string `mapstructure:"path" cty:"path" hcl:"path"`
	SHA256            *string `mapstructure:"sha256" cty:"sha256" hcl:"sha256"`
	ContentDigest     *string `mapstructure:"content_digest" cty:"content_digest" hcl:"content_digest"`
	SSHPrivateKeyFile *string `mapstructure:"ssh_private_key_file" cty:"ssh_private_key_file" hcl:"ssh_private_key_file"`
}

// FlatMapstructure returns a new FlatDatasourceOutput.
// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a DatasourceOutput.
// This spec is used by HCL to read the fields of DatasourceOutput.
// The decoded values from this spec will then be applied to a FlatDatasourceOutput.
func (*FlatDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"path":                 &hcldec.AttrSpec{Name: "path", Type: cty.String, Required: false},
		"sha256":               &hcldec.AttrSpec{Name: "sha256", Type: cty.String, Required: false},
		"content_digest":       &hcldec.AttrSpec{Name: "content_digest", Type: cty.String, Required: false},
		"ssh_private_key_file": &hcldec.AttrSpec{Name: "ssh_private_key_file", Type: cty.String, Required: false},
	}
	return s
}
