package payload

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/Mavergreen/packer-plugin-macosx"
	"github.com/Mavergreen/packer-plugin-macosx/internal/config"
	"github.com/Mavergreen/packer-plugin-macosx/internal/proc"
)

// Identifier and Version are the package's own identity, fixed.
const (
	Identifier = "com.mqg.firstboot"
	Version    = "1.0"
)

// confHeader is the first line of every firstboot.conf, byte for byte.
// docs/decisions/0011 fixes a conf built with updates "none" as the
// performance baseline, so a change to this line is a change to that
// baseline's bytes: make one only on purpose.
const confHeader = "# Generated by packer-plugin-macosx. Do not edit.\n"

// Config is a first-boot package's parameters, one field each.
type Config struct {
	User      string
	RealName  string
	Hostname  string
	Shell     string
	UID       int
	GID       int
	AutoLogin bool
	Password  string

	// Sudo, when true, gives User passwordless sudo through
	// /etc/sudoers.d/<User> (assets/guest/firstboot.sh's "passwordless
	// sudo" section): mode 0440, installed only after firstboot.sh's own
	// `visudo -cf` accepts it. Vagrant's darwin guest halt capability
	// runs `sudo shutdown -h now`, which needs exactly this.
	Sudo bool

	SSHKey string

	// OpenSSHPkgs are paths to the guest's own OpenSSH product archives
	// (internal/fetch's OpenSSH); their basenames are what firstboot.conf
	// carries and firstboot.sh installs.
	//
	// Plain paths, unlike UpdatePkgs, because here a path's base IS the
	// media's name: fetch caches each package under its release asset
	// name (cache/<sha>/<the name SHA256SUMS gives>), and the media
	// carries an extra package under its path's base. Nothing renames an
	// OpenSSH package on the way.
	OpenSSHPkgs []string
	OpenSSHTag  string

	// UpdatePkgs are Apple's post-10.9.5 update packages, IN INSTALL
	// ORDER (internal/fetch's updateSources table, in install order),
	// each with the name the installer media presents it under:
	// fetch.Update.Staged (fetch.StagedName), never the base of the
	// cache path, which is Apple's own name.
	UpdatePkgs []MediaFile
	Updates    string
}

// MediaFile is a package the installer media carries. Path is the file
// on this host, validated as a flat package; Name is what the media
// presents it as, and what firstboot.conf tells the guest to copy off the
// media (assets/guest/postinstall's carry_pkgs looks for exactly that
// name). Name must be a plain base name. For an update it is
// fetch.Update.Staged, not filepath.Base(Path): the two differ, and a
// conf naming the wrong one leaves the guest without the package.
type MediaFile struct{ Path, Name string }

// DefaultConfig is the first-boot defaults: user mavsuser, uid 501, gid
// 20 (staff), realname "Mavericks User", hostname mavericks, shell
// /bin/bash, auto-login on, no password, no sudo, no OpenSSH, updates
// none.
func DefaultConfig() Config {
	return Config{
		User:      "mavsuser",
		RealName:  "Mavericks User",
		Hostname:  "mavericks",
		Shell:     "/bin/bash",
		UID:       501,
		GID:       20,
		AutoLogin: true,
		Updates:   "none",
	}
}

// VagrantDefaults is DefaultConfig for a Vagrant-compatible box: user
// vagrant, uid 501 (Vagrant's own convention for a base box's default
// account), realname "Vagrant", and passwordless sudo.
//
// # SSHKey IS LEFT EMPTY, ON PURPOSE
//
// VagrantDefaults creates no file and touches no disk: it is a pure
// function of no arguments, like DefaultConfig, and Config.SSHKey is a
// path validateConfig reads with os.ReadFile -- a path this function has
// no business inventing, since a temp file it made would have no owner
// to remove it. VagrantPublicKey below is the bytes half of this same
// default; a caller that means to Build with them writes
// VagrantPublicKey() to a path of its own choosing (its own cache,
// typically, as the media data source does) and sets SSHKey to that
// path, exactly as it would for any other authorized key. See
// TestVagrantDefaultsLeavesSSHKeyEmpty and
// TestVagrantDefaultsCreatesNoFile.
func VagrantDefaults() Config {
	return VagrantAccount("vagrant")
}

// VagrantAccount is VagrantDefaults for the account user: the same
// uid, sudo and everything else, with the full name following the
// user. Vagrant's own user is "Vagrant", as its base boxes name it;
// any other user's full name is the user name itself, rather than a
// "Vagrant" that names someone else's account.
func VagrantAccount(user string) Config {
	c := DefaultConfig()
	c.User = user
	c.RealName = user
	if user == "vagrant" {
		c.RealName = "Vagrant"
	}
	c.Sudo = true
	return c
}

// VagrantPublicKey is Vagrant's own insecure RSA public key
// (assets/vagrant/vagrant.pub.rsa), the authorized-key half of
// VagrantDefaults' account -- which Vagrant itself replaces with a
// freshly generated key at the first `vagrant up`
// (assets/vagrant/README.md).
//
// RSA ONLY, NOT THE RSA+ED25519 PAIR VAGRANT ITSELF PUBLISHES TOGETHER
//
// validateKey refuses an Ed25519 authorized-key line outright when
// hasOpenSSH is false: stock OS X 10.9's OpenSSH 6.2 cannot parse one.
// VagrantDefaults' own OpenSSHPkgs is empty -- carrying the family's
// replacement OpenSSH is a caller's choice, not this function's default
// -- so a default authorized key carrying both would make a build from
// VagrantDefaults fail validateConfig the moment its SSHKey pointed at
// it. See TestVagrantPublicKeyIsRSAOnly.
//
// Bytes, not a path -- symmetric with VagrantPrivateKey below, and for
// the same reason: reading it can only fail from a corrupt binary,
// guaranteed present by embed.go's //go:embed line and
// TestEmbeddedFilesAreTheFilesOnDisk, so a failure here panics rather
// than adding an error return nothing else in this package needs.
func VagrantPublicKey() []byte {
	key, err := fs.ReadFile(macosx.Files, "assets/vagrant/vagrant.pub.rsa")
	if err != nil {
		panic(fmt.Sprintf("assets/vagrant/vagrant.pub.rsa not embedded: %v", err))
	}
	return key
}

// VagrantPrivateKey is the private half of the RSA keypair
// VagrantPublicKey returns, for the build's own SSH communicator to log
// in with (assets/vagrant/vagrant-standard-insecure-first-boot-only.key.rsa).
// Bytes, not a path: there
// is no Config field for a communicator's own key, and the one caller
// that needs this (the media data source's ssh_private_key_file output)
// writes it to its own cache path.
//
// PUBLIC BY DESIGN, NOT A SECRET: Vagrant publishes this keypair
// specifically so base-box creators can embed it (assets/vagrant/README.md).
// TestNoEmbeddedAssetCarriesAPublicKey and TestFirstbootShNeverEmbedsASecret
// are scoped away from assets/vagrant/ for exactly this reason -- this
// function's whole job is to hand back what those tests elsewhere forbid.
//
// Reading it can only fail from a corrupt binary: guaranteed present by
// embed.go's //go:embed line and TestEmbeddedFilesAreTheFilesOnDisk, so a
// failure here panics rather than adding an error return nothing else in
// this package needs.
func VagrantPrivateKey() []byte {
	key, err := fs.ReadFile(macosx.Files, "assets/vagrant/vagrant-standard-insecure-first-boot-only.key.rsa")
	if err != nil {
		panic(fmt.Sprintf("assets/vagrant/vagrant-standard-insecure-first-boot-only.key.rsa not embedded: %v", err))
	}
	return key
}

func boolDigit(b bool) string {
	if b {
		return "1"
	}
	return "0"
}

// spaceBasenames is `for p in $paths; do printf '%s ' "$(basename "$p")"; done`:
// each basename followed by one space, in the order given.
func spaceBasenames(paths []string) string {
	var b strings.Builder
	for _, p := range paths {
		b.WriteString(filepath.Base(p))
		b.WriteByte(' ')
	}
	return b.String()
}

// spaceNames is spaceBasenames for media files: each Name (never the base
// of its Path) followed by one space, in the order given.
func spaceNames(files []MediaFile) string {
	var b strings.Builder
	for _, f := range files {
		b.WriteString(f.Name)
		b.WriteByte(' ')
	}
	return b.String()
}

// quoteField is bashQuote with the field name attached to any error, so a
// value that cannot be quoted says which Config field it came from.
func quoteField(field, val string) (string, error) {
	q, err := bashQuote(val)
	if err != nil {
		return "", fieldErrorf(field, "%w", err)
	}
	return q, nil
}

// fieldErrorf is fmt.Errorf with a Config field name prefixed, for every
// error Build and its validation report: "every error names the field or
// path it concerns". The inner fmt.Errorf(format, a...) passes format and
// a straight through, in that order, which is the shape go vet's printf
// analyzer recognises as a wrapper -- so a call site's arguments are
// still checked against its own format string, the same as any direct
// fmt.Errorf call. (Confirmed by temporarily planting a mismatched call
// and re-running go vet; the plant was not committed.) The outer call's
// own format is the literal "%s: %w", not a field name, so this also
// never trips staticcheck's capitalized-error-string check (ST1005) the
// way a literal "Updates: ..." would.
func fieldErrorf(field, format string, a ...any) error {
	return fmt.Errorf("%s: %w", field, fmt.Errorf(format, a...))
}

// Conf renders firstboot.conf: the header, the account fields, MQG_FB_ADMIN_GID
// (fixed at 80, macOS's admin group, never configurable), the
// OpenSSH block, the updates block (only when there are packages to
// name), and the password (only when set). Every value is bashQuote'd.
func Conf(c Config) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(confHeader)

	type kv struct{ field, key, val string }
	line := func(f kv) error {
		q, err := quoteField(f.field, f.val)
		if err != nil {
			return err
		}
		fmt.Fprintf(&b, "%s=%s\n", f.key, q)
		return nil
	}

	for _, f := range []kv{
		{"User", "MQG_FB_USER", c.User},
		{"UID", "MQG_FB_UID", strconv.Itoa(c.UID)},
		{"GID", "MQG_FB_GID", strconv.Itoa(c.GID)},
	} {
		if err := line(f); err != nil {
			return nil, err
		}
	}
	b.WriteString("MQG_FB_ADMIN_GID=80\n")

	for _, f := range []kv{
		{"RealName", "MQG_FB_REALNAME", c.RealName},
		{"Shell", "MQG_FB_SHELL", c.Shell},
		{"Hostname", "MQG_FB_HOSTNAME", c.Hostname},
		{"AutoLogin", "MQG_FB_AUTOLOGIN", boolDigit(c.AutoLogin)},
		{"Sudo", "MQG_FB_SUDO", boolDigit(c.Sudo)},
	} {
		if err := line(f); err != nil {
			return nil, err
		}
	}

	if len(c.OpenSSHPkgs) > 0 {
		b.WriteString("MQG_FB_OPENSSH=1\n")
		if err := line(kv{"OpenSSHTag", "MQG_FB_OPENSSH_TAG", c.OpenSSHTag}); err != nil {
			return nil, err
		}
		if err := line(kv{"OpenSSHPkgs", "MQG_FB_EXTRA_PKGS", spaceBasenames(c.OpenSSHPkgs)}); err != nil {
			return nil, err
		}
	} else {
		b.WriteString("MQG_FB_OPENSSH=0\n")
	}

	// Written only when there is something to say: a conf built with
	// updates "none" has no updates lines at all (docs/decisions/0011).
	// See TestANoneConfSaysNothingAboutUpdates.
	if len(c.UpdatePkgs) > 0 {
		if err := line(kv{"Updates", "MQG_FB_UPDATES", c.Updates}); err != nil {
			return nil, err
		}
		if err := line(kv{"UpdatePkgs", "MQG_FB_UPDATE_PKGS", spaceNames(c.UpdatePkgs)}); err != nil {
			return nil, err
		}
	}

	if c.Password != "" {
		if err := line(kv{"Password", "MQG_FB_PASSWORD", c.Password}); err != nil {
			return nil, err
		}
	}

	return b.Bytes(), nil
}

// embedMarker is the line Postinstall substitutes in
// assets/guest/postinstall.
const embedMarker = "#MQG_EMBEDDED_FILES\n"

// embedBlock writes one of Postinstall's four blocks: say, a quoted
// heredoc, then a chmod. Content with no trailing newline would put the
// heredoc's terminator on the SAME line as its last line, where it does
// not terminate anything; a missing trailing newline gets one appended
// before the terminator, so the heredoc always closes. See
// TestAMissingTrailingNewlineStillTerminatesTheHeredoc.
func embedBlock(b *bytes.Buffer, v, dst, mode string, content []byte) {
	fmt.Fprintf(b, "say \"writing %s\"\n", dst)
	fmt.Fprintf(b, "cat > \"%s\" <<'MQG_EOF_%s'\n", dst, v)
	b.Write(content)
	if len(content) == 0 || content[len(content)-1] != '\n' {
		b.WriteByte('\n')
	}
	fmt.Fprintf(b, "MQG_EOF_%s\n", v)
	fmt.Fprintf(b, "chmod %s \"%s\" 2>/dev/null\n\n", mode, dst)
}

// Postinstall assembles the package's one Scripts member: the embedded
// assets/guest/postinstall template with its #MQG_EMBEDDED_FILES line
// replaced by four heredocs -- firstboot.sh, conf, the authorized key and
// the LaunchDaemon plist. $CONF_DIR and $DAEMON are written
// literally: they are variables for the installed script to expand on the
// guest, not here.
func Postinstall(conf, key []byte) ([]byte, error) {
	template, err := fs.ReadFile(macosx.Files, "assets/guest/postinstall")
	if err != nil {
		return nil, err
	}
	firstbootSh, err := fs.ReadFile(macosx.Files, "assets/guest/firstboot.sh")
	if err != nil {
		return nil, err
	}
	plist, err := fs.ReadFile(macosx.Files, "assets/guest/com.mqg.firstboot.plist")
	if err != nil {
		return nil, err
	}

	var body bytes.Buffer
	embedBlock(&body, "FIRSTBOOT_SH", "$CONF_DIR/firstboot.sh", "755", firstbootSh)
	embedBlock(&body, "FIRSTBOOT_CONF", "$CONF_DIR/firstboot.conf", "600", conf)
	embedBlock(&body, "AUTHORIZED_KEYS", "$CONF_DIR/authorized_keys", "644", key)
	embedBlock(&body, "LAUNCHDAEMON", "$DAEMON", "644", plist)

	idx := bytes.Index(template, []byte(embedMarker))
	if idx < 0 {
		return nil, fmt.Errorf("assets/guest/postinstall has no %s line to substitute", strings.TrimSuffix(embedMarker, "\n"))
	}
	out := make([]byte, 0, len(template)+body.Len())
	out = append(out, template[:idx]...)
	out = append(out, body.Bytes()...)
	out = append(out, template[idx+len(embedMarker):]...)
	return out, nil
}

var keyLineRE = regexp.MustCompile(`(?m)^(ssh|ecdsa)-`)

// keyLines is every non-empty, non-comment line of an authorized_keys
// file, trimmed: what carries a key. A line whose first non-whitespace
// character is '#' is a comment and is never a key -- not for the
// Ed25519 refusal below, not for the per-line "may not understand it"
// warning, and not for Build's "authorized key:" log line.
//
// Looking at the first line alone would miss a key file with a
// `# my laptop key` comment above an Ed25519 key -- letting through a key
// the guest cannot use, and making Build's "authorized key:" log line
// print "#", not the key's real type. Scanning every non-comment line
// gets both right: see TestKeyRules.
func keyLines(key []byte) []string {
	var out []string
	for _, line := range strings.Split(string(key), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	return out
}

// validateKey applies the SSH key rules to an already-read key file,
// given by path only for error messages.
//
// The PRIVATE-key check runs before the check for a line starting
// ssh-/ecdsa-: a real OpenSSH private key has no such line, and would
// otherwise be refused with "does not look like an SSH public key"
// rather than the more specific PRIVATE message. See TestKeyRules.
func validateKey(path string, key []byte, hasOpenSSH bool, tag string, log func(string, ...any)) error {
	head := key
	if len(head) > 64 {
		head = head[:64]
	}
	if bytes.Contains(head, []byte("PRIVATE")) {
		return fieldErrorf("SSHKey", "%s looks like a PRIVATE key; pass the .pub", path)
	}
	if !keyLineRE.Match(key) {
		return fieldErrorf("SSHKey", "%s does not look like an SSH public key", path)
	}

	lines := keyLines(key)

	// The Ed25519 refusal looks at EVERY non-comment line, not just the
	// first: see keyLines' comment. Checked in its own pass, before any warning, so a later
	// line's refusal is never preceded by an earlier line's warning.
	if !hasOpenSSH {
		for _, line := range lines {
			typ := strings.Fields(line)[0]
			if strings.Contains(typ, "ed25519") {
				return fieldErrorf("SSHKey", "%s is an Ed25519 key, and a stock OS X 10.9 guest cannot use one: "+
					"it ships OpenSSH 6.2, and Ed25519 arrived in 6.5. Build the image with the family's OpenSSH "+
					"(the default: openssh = true), or use an RSA or ECDSA key: "+
					"ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa", path)
			}
		}
	}

	for _, line := range lines {
		typ := strings.Fields(line)[0]
		var ok bool
		if hasOpenSSH {
			ok = slices.Contains([]string{"ssh-ed25519", "ssh-rsa", "ssh-dss"}, typ) ||
				strings.HasPrefix(typ, "ecdsa-sha2-") || strings.HasPrefix(typ, "sk-")
		} else {
			ok = slices.Contains([]string{"ssh-rsa", "ssh-dss"}, typ) || strings.HasPrefix(typ, "ecdsa-sha2-")
		}
		if ok || log == nil {
			continue
		}
		if hasOpenSSH {
			log("%s is a %s key; OpenSSH %s may not understand it", path, typ, tag)
		} else {
			log("%s is a %s key; OS X 10.9's OpenSSH 6.2 may not understand it", path, typ)
		}
	}
	return nil
}

// validatePkgs applies the package rules to a Config field's list of
// package paths: each must exist, carry
// the xar magic, and have a basename with no whitespace (the names travel
// through a space-separated shell list in firstboot.conf).
func validatePkgs(field string, pkgs []string) error {
	for _, p := range pkgs {
		if _, err := os.Stat(p); err != nil {
			return fieldErrorf(field, "no such package: %s", p)
		}
		ok, err := hasXarMagic(p)
		if err != nil {
			return fieldErrorf(field, "%s: %w", p, err)
		}
		if !ok {
			return fieldErrorf(field, "%s is not a flat package (no xar magic)", p)
		}
		base := filepath.Base(p)
		if strings.ContainsAny(base, " \t\n\r\v\f") {
			return fieldErrorf(field, "name contains whitespace: %s", base)
		}
	}
	return nil
}

// validateMediaFiles is validatePkgs for media files: each Path exactly
// as validatePkgs checks a path, and each Name a plain base name -- not
// empty, not "." or "..", no "/" -- with no whitespace, since it is the
// Name that travels through firstboot.conf's space-separated list.
func validateMediaFiles(field string, files []MediaFile) error {
	for _, f := range files {
		if err := validatePkgs(field, []string{f.Path}); err != nil {
			return err
		}
		if f.Name == "" || f.Name == "." || f.Name == ".." || strings.Contains(f.Name, "/") {
			return fieldErrorf(field, "%s: media name %q is not a plain file name", f.Path, f.Name)
		}
		if strings.ContainsAny(f.Name, " \t\n\r\v\f") {
			return fieldErrorf(field, "media name contains whitespace: %s", f.Name)
		}
	}
	return nil
}

// validateConfig applies every rule that can be checked before
// assembling anything: the key first, then the packages and the updates
// selection. It returns the key file's bytes, read once, so Build need not read it
// again.
func validateConfig(c Config, log func(string, ...any)) ([]byte, error) {
	if c.SSHKey == "" {
		return nil, fieldErrorf("SSHKey", "no SSH public key given")
	}
	key, err := os.ReadFile(c.SSHKey)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fieldErrorf("SSHKey", "no such SSH public key: %s", c.SSHKey)
		}
		return nil, fieldErrorf("SSHKey", "%w", err)
	}
	hasOpenSSH := len(c.OpenSSHPkgs) > 0
	if err := validateKey(c.SSHKey, key, hasOpenSSH, c.OpenSSHTag, log); err != nil {
		return nil, err
	}

	if err := validatePkgs("OpenSSHPkgs", c.OpenSSHPkgs); err != nil {
		return nil, err
	}
	if hasOpenSSH && c.OpenSSHTag == "" {
		return nil, fieldErrorf("OpenSSHTag", "required when OpenSSHPkgs is set -- "+
			"an image must record which OpenSSH it was built with")
	}

	if err := validateMediaFiles("UpdatePkgs", c.UpdatePkgs); err != nil {
		return nil, err
	}
	if !slices.Contains(config.UpdateChoices, c.Updates) {
		return nil, fieldErrorf("Updates", "unknown %q: choose one of %s", c.Updates, strings.Join(config.UpdateChoices, ", "))
	}
	if len(c.UpdatePkgs) > 0 && c.Updates == "none" {
		return nil, fieldErrorf("UpdatePkgs", "given but Updates is \"none\"; "+
			"the image would carry packages it does not admit to")
	}
	if len(c.UpdatePkgs) == 0 && c.Updates != "none" {
		return nil, fieldErrorf("Updates", "%q names no packages", c.Updates)
	}

	return key, nil
}

// Build validates c, assembles firstboot.conf and the postinstall script,
// checks the result is valid shell (via r, so a fake can refuse it in a
// test), packages it with flatPackage, and writes out and its out.sha256
// sidecar -- both by writing a temp file and renaming it into place, so a
// reader never sees a partial file. It returns the package's own sha256.
func Build(ctx context.Context, r proc.Runner, c Config, out string, log func(string, ...any)) (string, error) {
	if log == nil {
		log = func(string, ...any) {}
	}

	key, err := validateConfig(c, log)
	if err != nil {
		return "", err
	}

	conf, err := Conf(c)
	if err != nil {
		return "", err
	}
	post, err := Postinstall(conf, key)
	if err != nil {
		return "", err
	}

	tmp, err := os.CreateTemp("", "mqg-postinstall-*")
	if err != nil {
		return "", err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := tmp.Write(post); err != nil {
		tmp.Close()
		return "", err
	}
	if err := tmp.Close(); err != nil {
		return "", err
	}
	var stderr bytes.Buffer
	if err := r.Run(ctx, proc.Cmd{Name: "sh", Args: []string{"-n", tmpName}, Stderr: &stderr}); err != nil {
		if msg := strings.TrimSpace(stderr.String()); msg != "" {
			return "", fmt.Errorf("the assembled postinstall is not valid shell: %s: %w", msg, err)
		}
		return "", fmt.Errorf("the assembled postinstall is not valid shell: %w", err)
	}

	pkg, err := flatPackage(post, Identifier, Version)
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return "", err
	}
	if err := writeOutput(out, pkg); err != nil {
		return "", err
	}

	h := sha256.Sum256(pkg)
	sum := hex.EncodeToString(h[:])
	sidecar := fmt.Sprintf("%s  %s\n", sum, filepath.Base(out))
	if err := writeOutput(out+".sha256", []byte(sidecar)); err != nil {
		return "", err
	}

	log("built %s (%d bytes), sha256 %s", out, len(pkg), sum)
	for _, line := range keyLines(key) {
		fields := strings.Fields(line)
		typ, body := fields[0], ""
		if len(fields) > 1 {
			body = fields[1]
		}
		if len(body) > 16 {
			body = body[:16]
		}
		log("authorized key: %s %s...", typ, body)
	}

	return sum, nil
}

// writeOutput writes data to path through a fresh, uniquely named temp
// in path's own directory (os.CreateTemp: O_EXCL, so nothing already at
// some fixed temp name is ever opened and written through), synced, made
// 0644, then renamed into place: a reader never sees a partial file. The
// temp is removed on any failure. Build uses this for both the package
// and its out.sha256 sidecar. (fetch has its own writer for the cache,
// writeCacheFile: payload does not import fetch.)
func writeOutput(path string, data []byte) (err error) {
	f, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".*.tmp")
	if err != nil {
		return err
	}
	tmp := f.Name()
	defer func() {
		if err != nil {
			f.Close()
			os.Remove(tmp)
		}
	}()
	if _, err := f.Write(data); err != nil {
		return err
	}
	if err := f.Sync(); err != nil {
		return err
	}
	if err := f.Chmod(0o644); err != nil {
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
