// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package firmware

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	SMBIOS   *string `mapstructure:"smbios" cty:"smbios" hcl:"smbios"`
	Debug    *bool   `mapstructure:"debug" cty:"debug" hcl:"debug"`
	Ccache   *bool   `mapstructure:"ccache" cty:"ccache" hcl:"ccache"`
	Compiler *string `mapstructure:"compiler" cty:"compiler" hcl:"compiler"`
	CacheDir *string `mapstructure:"cache_dir" cty:"cache_dir" hcl:"cache_dir"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"smbios":    &hcldec.AttrSpec{Name: "smbios", Type: cty.String, Required: false},
		"debug":     &hcldec.AttrSpec{Name: "debug", Type: cty.Bool, Required: false},
		"ccache":    &hcldec.AttrSpec{Name: "ccache", Type: cty.Bool, Required: false},
		"compiler":  &hcldec.AttrSpec{Name: "compiler", Type: cty.String, Required: false},
		"cache_dir": &hcldec.AttrSpec{Name: "cache_dir", Type: cty.String, Required: false},
	}
	return s
}

// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDatasourceOutput struct {
	OVMFCode      *string `mapstructure:"ovmf_code" cty:"ovmf_code" hcl:"ovmf_code"`
	OVMFVars      *string `mapstructure:"ovmf_vars" cty:"ovmf_vars" hcl:"ovmf_vars"`
	OpenCoreImage *string `mapstructure:"opencore_image" cty:"opencore_image" hcl:"opencore_image"`
	SHA256Sums    *string `mapstructure:"sha256sums" cty:"sha256sums" hcl:"sha256sums"`
}

// FlatMapstructure returns a new FlatDatasourceOutput.
// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a DatasourceOutput.
// This spec is used by HCL to read the fields of DatasourceOutput.
// The decoded values from this spec will then be applied to a FlatDatasourceOutput.
func (*FlatDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"ovmf_code":      &hcldec.AttrSpec{Name: "ovmf_code", Type: cty.String, Required: false},
		"ovmf_vars":      &hcldec.AttrSpec{Name: "ovmf_vars", Type: cty.String, Required: false},
		"opencore_image": &hcldec.AttrSpec{Name: "opencore_image", Type: cty.String, Required: false},
		"sha256sums":     &hcldec.AttrSpec{Name: "sha256sums", Type: cty.String, Required: false},
	}
	return s
}
