// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package snowleopardinstaller

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Path           *string `mapstructure:"path" cty:"path" hcl:"path"`
	PrivopsTimeout *string `mapstructure:"privops_timeout" cty:"privops_timeout" hcl:"privops_timeout"`
	CacheDir       *string `mapstructure:"cache_dir" cty:"cache_dir" hcl:"cache_dir"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"path":            &hcldec.AttrSpec{Name: "path", Type: cty.String, Required: false},
		"privops_timeout": &hcldec.AttrSpec{Name: "privops_timeout", Type: cty.String, Required: false},
		"cache_dir":       &hcldec.AttrSpec{Name: "cache_dir", Type: cty.String, Required: false},
	}
	return s
}

// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDatasourceOutput struct {
	Path  *string `mapstructure:"path" cty:"path" hcl:"path"`
	Build *string `mapstructure:"build" cty:"build" hcl:"build"`
}

// FlatMapstructure returns a new FlatDatasourceOutput.
// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a DatasourceOutput.
// This spec is used by HCL to read the fields of DatasourceOutput.
// The decoded values from this spec will then be applied to a FlatDatasourceOutput.
func (*FlatDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"path":  &hcldec.AttrSpec{Name: "path", Type: cty.String, Required: false},
		"build": &hcldec.AttrSpec{Name: "build", Type: cty.String, Required: false},
	}
	return s
}
