// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package snowleopardmedia

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Installer      *string `mapstructure:"installer" cty:"installer" hcl:"installer"`
	User           *string `mapstructure:"user" cty:"user" hcl:"user"`
	AuthorizedKey  *string `mapstructure:"authorized_key" cty:"authorized_key" hcl:"authorized_key"`
	Updates        *string `mapstructure:"updates" cty:"updates" hcl:"updates"`
	ExtraSpaceMiB  *int    `mapstructure:"extra_space_mib" cty:"extra_space_mib" hcl:"extra_space_mib"`
	PrivopsTimeout *string `mapstructure:"privops_timeout" cty:"privops_timeout" hcl:"privops_timeout"`
	CacheDir       *string `mapstructure:"cache_dir" cty:"cache_dir" hcl:"cache_dir"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"installer":       &hcldec.AttrSpec{Name: "installer", Type: cty.String, Required: false},
		"user":            &hcldec.AttrSpec{Name: "user", Type: cty.String, Required: false},
		"authorized_key":  &hcldec.AttrSpec{Name: "authorized_key", Type: cty.String, Required: false},
		"updates":         &hcldec.AttrSpec{Name: "updates", Type: cty.String, Required: false},
		"extra_space_mib": &hcldec.AttrSpec{Name: "extra_space_mib", Type: cty.Number, Required: false},
		"privops_timeout": &hcldec.AttrSpec{Name: "privops_timeout", Type: cty.String, Required: false},
		"cache_dir":       &hcldec.AttrSpec{Name: "cache_dir", Type: cty.String, Required: false},
	}
	return s
}
